apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: memory
      target:
        #averageUtilization: 100
        #type: Utilization
        type: AverageValue
        averageValue: 30Mi
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web

